package ca.mcgill.ecse223.quoridor.view.event;

import ca.mcgill.ecse223.quoridor.controller.Orientation;

/**
 * A listener for events generated by the tile-map panel
 *
 * @author Paul Teng (260862906)
 */
public interface GameBoardListener {

    /**
     * This is called when the mouse wheel rotates
     *
     * @param clicks The amount the wheel rotated
     */
    public void onMouseWheelRotated(double clicks);

    /**
     * This is called when any pawn tile is clicked on
     *
     * @param row Row in pawn coordinates
     * @param col Column in pawn coordinates
     */
    public void onTileClicked(int row, int col);

    /**
     * This is called when mouse enters any pawn tile
     *
     * @param row Row in pawn coordinates
     * @param col Column in pawn coordinates
     */
    public void onTileEntered(int row, int col);

    /**
     * This is called when mouse leaves any pawn tile
     *
     * @param row Row in pawn coordinates
     * @param col Column in pawn coordinates
     */
    public void onTileExited(int row, int col);

    /**
     * This is called when any wall slot is clicked on
     *
     * @param row         Row in wall coordinates
     * @param col         Column in wall coordinates
     * @param orientation Orientation
     */
    public void onSlotClicked(int row, int col, Orientation orientation);

    /**
     * This is called when mouse enters any wall slot
     *
     * @param row         Row in wall coordinates
     * @param col         Column in wall coordinates
     * @param orientation Orientation
     */
    public void onSlotEntered(int row, int col, Orientation orientation);

    /**
     * This is called when mouse leaves any wall slot
     *
     * @param row         Row in wall coordinates
     * @param col         Column in wall coordinates
     * @param orientation Orientation
     */
    public void onSlotExited(int row, int col, Orientation orientation);
}